# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chpmunk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chpmunk
  pod 'Firebase/Core'

  target 'ChpmunkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChpmunkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
